// export { default as Navbar } from "./Navbar/Navbar";
export { default as Navbar2 } from "./Navbar/Navbar2";
export { default as Hero } from "./Hero/Hero";
export { default as About } from "./About/About";
// export { default as Header } from "./Header/Header";
export { default as Work } from "./Work/Work";
export { default as Skills } from "./Skills/Skills";
// export { default as Services } from "./Services/Services";
export { default as Contact } from "./Contact/Contact";
// export { default as Footer } from "./Footer/Footer";
